### ISSUE TITLE
Combine body hair into one line in health tab

### ISSUE THREAD

**Issue by inexcode** [inexcode/HumanlikeLifeStages#6]
As [James009](https://steamcommunity.com/id/James009) suggested on Steam:

> I'd highly recommend getting rid of the body hair for each individual body part and just make it universal where it is scaled from none to bearlike (with like four variations). It really clutters up the medical menu right now. Might want to also buff the cold weather bonus from it a bit.

Probably should try using different HediffCompProperties, which are used for infections in the core game, or take a look if a new UI may be created for the pop-up.

**Comment by WinstontheButterfly** [comment]
I agree with this but say we have like 5 levels of body hair: Baby Smooth, Light, Medium, Heavy and Bear Like

**Comment by HakariTenrai** [comment]
I do not have a medicine tab, so I'm not sure exactly what this suggestion is... but think it's asking for all of the parts to be condensed down to just a single option for body hair?... I would be fine with that, if another separate option is added for facial hair (beards), the same way we already have a separate option for pubic hair...

I'd also like to see more options added for all hair types: Hairless, Clean Shaven, Light, Noticeable, Prevalent, Bearlike.

Hairless and clean shaven are not the same thing... Elves, for example, are often portrayed as having hairless bodies (other than their heads).

With my suggestion, a tribesman can have bearlike body hair, and a clean shaven jaw, and my male elves could have hairless bodies, but include an option for facial hair on their jaw to have a beard.

For the op of this thread, I would support a configurable toggle in the options to make it so that the hair feature can be applied either to the whole body, as a single feature, or to individual parts.... but if that cannot be done, then I'd rather keep it as individual parts, and even add more options.

What I would not want, would for me to be forced to chose either "body hair" or "no body hair" as my only options...

**Comment by WinstontheButterfly** [comment]
if we keep all the options as a configurable toggle then we should make them Prepare carefully compatible because they are not currently.

**Comment by inexcode** [comment]
> I do not have a medicine tab

Sorry, I meant "health" tab.
The goal of this issue is not to downgrade the variety of body hair, but to display it in a much more convenient way.
